// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFKZaegd2Kra2wpQyu-xy2_DNgpBMGI54',
    appId: '1:379065380713:web:238e1b4efa21d0ec5957f8',
    messagingSenderId: '379065380713',
    projectId: 'quandry-46ed9',
    authDomain: 'quandry-46ed9.firebaseapp.com',
    storageBucket: 'quandry-46ed9.firebasestorage.app',
    measurementId: 'G-1HGHL6KB14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbUeHmxRYuyErV3Wivlv66qF29v-84lmw',
    appId: '1:379065380713:android:430c56946d6af21f5957f8',
    messagingSenderId: '379065380713',
    projectId: 'quandry-46ed9',
    storageBucket: 'quandry-46ed9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWR01KZdQclb-oYFsmnN9DjCz6ZCRObuU',
    appId: '1:379065380713:ios:35ff49f64cef22555957f8',
    messagingSenderId: '379065380713',
    projectId: 'quandry-46ed9',
    storageBucket: 'quandry-46ed9.firebasestorage.app',
    iosBundleId: 'com.example.quandry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWR01KZdQclb-oYFsmnN9DjCz6ZCRObuU',
    appId: '1:379065380713:ios:35ff49f64cef22555957f8',
    messagingSenderId: '379065380713',
    projectId: 'quandry-46ed9',
    storageBucket: 'quandry-46ed9.firebasestorage.app',
    iosBundleId: 'com.example.quandry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFKZaegd2Kra2wpQyu-xy2_DNgpBMGI54',
    appId: '1:379065380713:web:c36200a4f96295cf5957f8',
    messagingSenderId: '379065380713',
    projectId: 'quandry-46ed9',
    authDomain: 'quandry-46ed9.firebaseapp.com',
    storageBucket: 'quandry-46ed9.firebasestorage.app',
    measurementId: 'G-Q2N9PNLQ3R',
  );
}
